jqPlot/jqPlot

.gitignore
build.xml

Replaced hg executable with git alternatives to set HG_ID and REVISION variables in the ANT build script.
For issue #3

Changed build.xml

---

src/jqplot.core.js

The function `checkIntersection(gridpos, plot)` does not return an intersection for **negative** values in a waterfall plot. 
Specifically this plot: 
```javascript
renderer:$.jqplot.BarRenderer, rendererOptions:{waterfall:true} 
```
The fault impacts the use of the highlight plugin and mouse event handlers which rely on the checkIntersection function to return the intersection of the mouse cursor and bar. There are likely other impacts too.
The fault exists in inside 
```javascript
function checkIntersection(gridpos, plot)
```
:gem: **See the issue  #7  for more details**

Fix checkIntersection issue

---

src/jqplot.toImage.js

Hi,
I have a problem when converting my jqPlot image to an image, resulting in an infinite loop and making it impossible to make use of this functionality.
After some Googling I found the solution of  Edward Faulkner (https://bitbucket.org/ef4/jqplot/commits/a59e7e7a5e97ea721a7b8571612b334e8c025b36) which works for me (and other apparently).
But for some reason his pull request never made it (got lost in the transition to GitHub?)
Hence this Pull Request to actually include his fix after all.
What it does, is check if the w consists of more words than the current word. If not, it is not possible to break before the current word as it does not fit the available space (tagWidth). And breaking should be skipped.
As a result this fixes the 'infinite loop' issue.
Cheers,
Maarten

Fixing infinite loop

---

src/plugins/jqplot.pointLabels.js

Fixes JS-error on resizing for horizontal bar charts which have the option pointLables->hideZeros to true

Error resizing horizontal bar charts

---

examples/line-charts.php

No idea why it adds the newline, i suspect it is the webeditor of github doing weird things. The issue is the typo in the word "diamond" though.

Fixing a typo there

---

examples/pie-donut-charts.php
src/plugins/jqplot.donutRenderer.js

introduce "totalLabel" rendererOption for donut render to display the total amount of items in the center of the donut
Result looks like this:

new "totalLabel" rendererOption for donut renderer

---

src/jqplot.core.js

added missing code from http://stackoverflow.com/questions/20221461/hidpi-retina-plot-drawing to jqplot.core.js because high resolution support is broken without that. Fix for #38.

fix for #38 (pie charts not rendering because of highres support)

---

src/plugins/jqplot.donutRenderer.js

canvas.style.width and canvas.style.height must be used instead of canvas.width and canvas.height

fix for #47 (donut charts not rendering correctly because of highres support)

---

package.json

Hello
According to README.md, I think jqPlot is under both the `MIT` and `GPL version 2.0` licenses.

update license field in package.json

---

examples/barChartHightlighter.php
src/plugins/jqplot.highlighter.js

This is a fix for the same problem as reported in this old issue: https://bitbucket.org/cleonello/jqplot/issues/514 (and this pull request: https://bitbucket.org/cleonello/jqplot/pull-requests/22/fix-for-issue-514-adjusting-position-with/diff )
When using the bar renderer and the highlighter, with multiple bars, the marker shown by the highlighter appears at the correct Y coordinate (when using vertical bars) but the X coordinate value is always at the middle of the category (that is at the middle of all the bars within a given category), irrespectively of which bar/value is supposed to be highlighted.
This pull requests adds a first patch with a new example illustrating the problem. The second patch suggests a fix.

The highlighter point is always on the middle of a set of bars when using multiple bar series

---

examples/cursorAutoscaleConstraint.php
src/plugins/jqplot.cursor.js

(This is a slightly modified version of [this old pull request I submitted on BitBucket](https://bitbucket.org/cleonello/jqplot/pull-requests/60).)
This pull request provides support for the `autoscaleConstraint` option: when zooming with an `x` constraint, it can be useful to rescale the Y-axis to make better use of the range available.
I've added support for `autoscaleConstraint` in the cursor plugin. (There were a couple of lines meant to implement this in the existing code, but it wouldn't have done anything, even uncommented.)
When `constrainZoomTo: 'x'` is set in the `cursor` options, setting `autoscaleConstraint: true` will also automatically adapt the range of the Y-axes for the range zoomed in. This also respects the existing `min` or `ma`x options in the axes (these won't be …

Adding support for autoscaleConstraint in the cursor plugin.

---

examples/line-charts-variable-markers.php
src/jqplot.lineRenderer.js
src/jqplot.markerRenderer.js

This patch adds a `markerOptionsCallback` option that allows a callback to be specified so as to customise the marker options for an individual point. (There is also an example page with this patch.)
For example, if the values are negative, turn the marker red:
markerOptionsCallback: function(plot, series, idx, dataPoint, gridDataPoint) {
var opts =  { style:"diamond" };
if (dataPoint[1] < 0) {
opts.color = "red";
}
return opts;
}
If the point index is above 3, turn the marker yellow:
markerOptionsCallback: function(plot, series, idx, dataPoint, gridDataPoint) {
var opts =  {};
if (dataPoint[0] >3) {
opts.color = "yellow";
}
return opts;
}

Ability to customise individual point markers within a series

---

examples/highlighthingCursor.php
src/plugins/jqplot.highlightingCursor.js

This adds a new plugin for a highlighting cursor.
The main difference with the existing cursor and highlighter is that it will activate the markers for all neighbouring points around the cursor, whereas the normal highlighter would only activate the marker on the point close to where the mouse pointer is (not the vertical cursor).
This also comes with an `update` callback, which can be used to update other parts of the page when the cursor has been moved.
There is also an option that gives the user the ability to "freeze" the cursor at a position of interest by clicking (the mouse cursor can then be moved without losing that position).
This pull request comes with additional examples.

Highlighting cursor

---

src/plugins/jqplot.donutRenderer.js

Given thickness value <1, treat as a explicitly defined percentage to allow for dynamic size creation based on container size.

Allow percentage thickness values for donutRenderer

---

src/plugins/jqplot.dateAxisRenderer.js

(Same as [issue 611 on Bitbucket](https://bitbucket.org/cleonello/jqplot/issues/611).)
The attached image shows two examples using the same data (input in ms since Unix Epoch). When using the plain linear axis, the points are rendered as expected, but when using the date axis, some artificial variations are introduced. (On larger datasets, it can actually shift part of the plots, when multiple series would otherwise be synchronised.)

Using a date axis renderer sometimes distorts the data

---

src/jqplot.core.js

(This is the same problem as [Bitbucket issue 623](https://bitbucket.org/cleonello/jqplot/issues/623) and fix suggested in [Bitbucket PR 26](https://bitbucket.org/cleonello/jqplot/pull-requests/26).)
When using `outsideGrid` placement for the legend located south, the legend box is centred on the middle of the graph area, excluding the space taken by the Y-axes.
This can lead to legend boxes overflowing on the left, when there is a large number of Y-axes (particularly with the enhanced legend renderer).
The attached screenshot illustrates the problem. The legend box is cut off on the left, hitting the left end of the browser window, whereas there would have been enough space on the right-hand side to display the legend box on an area that includes the space taken by the Y-axes. (It's not …

outsideGrid south legends centering doesn't take into account axes shift

---

src/jqplot.toImage.js

`jqplot.toImage.js` was hiding the tooltips coming from the highlighter plugin, but not those from the canvasOverlay plugin. This patch fixes also hides those coming from canvasOverlay.
In the long term, it might be better to add a second class (e.g. `jqplot-toimage-hide`) to all tooltips or other elements to hide when rendering to an image, so as not to have this reference to plugin code from the core code. (I could try to improve this pull request accordingly depending on the feedback.)

Hide canvasOverlay tooltips when saving to image.

---

src/plugins/jqplot.dragable.js

Hello, this fixes the drag and drop when used with the bubble renderer: it was generating an error, making it slow.

bugfix on jqplot.dragable.js

---

src/plugins/jqplot.funnelRenderer.js

… big in canvas and broken.
Issue Detail:- With Version 1.0.9, funnelchart plot is very big in size and going out of canvas area.This happens only if devicepixelratio is >1 in any browser and in firefox whose pixelratio is -1.
Analysis:- Observed that in jquery.jqplot.js InitCanvas method,Canvas is set based on device pixelratio.But in plugin file funnelrenderer.js CSS Canvas width and height is not considered for plotting funnel chart within canvas.This is causing issue.
This was handled only in pierenderer in version 1.0.9.
Solution:- Applied CSS Canvas width and height in draw function of funnelrenderer. Chart comes-up fine irrespective of device pixel ratio in all browsers.

Funnel Chart Misaligned in Canvas Area in 1.0.9

---

src/plugins/jqplot.highlighter.js

Prevent left most tool-tip from appearing off screen.
When using jqplot within some existing applications. Often the left most tooltip is returned as a negative x coordinate value e.g. "left: -75.25px".
This causes tool-tips to appear out of frame. So capping left at 0 will prevent these issues.

Avoid tool-tip off screen

---

src/plugins/jqplot.meterGaugeRenderer.js

I applied the same change here as was previously applied in funnel renderer

Gauge is not rendered correctly when devicePixelRatio > 1

---

src/plugins/jqplot.pieRenderer.js

Fix issue #130 
it makes changes to function makeGridData in pieRenderer.js plugin..
It's not necessary changing enhancedPieLegendRenderer.js plugin, although, it makes sense and is useful along with the use of this plugin.

Fill all pie chart when hidding some slices of checked elements in the legend

---

src/plugins/jqplot.cursor.js

Fixes Internet Explorer bug, when cursor leaves the canvas while dragging and zooming.

Fix for IE drag/zoom error

---

src/plugins/jqplot.barRenderer.js

This PR firstly fixes a problem whereby the auto-calculated barWidth can be zero or negative, if there are a high number of bars to display and a relatively small amount of space. This is less of a problem than it
sounds, as a negative value is still displayed (but presumably offset than it should have been).
The PR also introduces a minimum width configuration option, set to 2 pixels by default.

Fix zero or negative auto barWidth and allow minimum value
